### ISSUE TITLE
remove `nb_header` field from `EDF.Header`

### ISSUE THREAD

**Issue by jrevels** [beacon-biosignals/EDF.jl#21]
Or at least allow it to be `missing`.

As a caller, it makes constructing `EDF.Header`s correctly a bit annoying; I might be naively missing something but I'm guessing it's generally better to calculate this on the fly in `EDF.write` (since it's already doing the work to calculate this field accurately) as opposed to requiring/relying on correct construction by the caller. 

cc @OTDE who ran into this a while ago IIRC

**Comment by ararslan** [comment]
I included it because it's stored in the EDF file's header section and is required for writing. I remember looking into this a while back and finding that it was difficult/annoying to compute in a way such that the resulting EDF was roundtripable. The use case of constructing any part of an EDF file manually was never really a consideration when designing this package, since for our purposes at the time we only needed to read EDFs. The current API for manually constructing any part of an EDF is completely awful.

**Comment by OTDE** [comment]
Specifically, this becomes an issue once EDF annotations enter the picture. It's a trivial calculation without them, but with them, it's kind of a nightmare. To get the requisite part of the pipeline up and running, I used Luna's `annot` file format to skip this sort of file byte counting chicanery. Luna also manually adds a time track to all the EDF files I give it and is fairly generous when parsing, so I haven't run into any problems related to this since that I've been able to identify.

**Comment by ararslan** [comment]
>  this becomes an issue once EDF annotations enter the picture

Ah right, now I remember: I did this back when I was adding support for EDF annotations.

**Comment by jrevels** [comment]
yup, luckily `EDF.write` has all the information for correctly calculating `nb_header` on its own, so we can solve the problem of calculating it in a single place + remove the field to alleviate the burden for callers to reimplement their own error-prone solutions for this

**Comment by ararslan** [comment]
Closed by #22.
